In [1]:
import pandas as pd 
import numpy as np

print("Libraries Loaded successfully")

Libraries Loaded successfully

#DATASET AUDIT

In [2]:
file_path ="../../01_Raw_Data/online_retail_II.xlsx"

sheet_1 = pd.read_excel(
    file_path, sheet_name= "Year 2010-2011"
)

print("Data Loaded Successfully")

Data Loaded Successfully

In [4]:
print("2009-2010 Shape:", sheet_1.shape)

2009-2010 Shape: (541910, 8)

In [8]:
file_path ="../../01_Raw_Data/online_retail_II.xlsx"

sheet_1 = pd.read_excel(
    file_path, sheet_name= "Year 2009-2010"
)
sheet_2= pd.read_excel(
    file_path,
    sheet_name = "Year 2010-2011"
)

print("Data Loaded Successfully")

Data Loaded Successfully

In [9]:
print("2009-2010 Shape:", sheet_1.shape)
print("2010-2011 Shape:", sheet_2.shape)

2009-2010 Shape: (525461, 8)
2010-2011 Shape: (541910, 8)

In [11]:
sheet_1.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [12]:
sheet_2.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [13]:
print(sheet_1.shape)
print(sheet_2.shape)

(525461, 8)
(541910, 8)

In [19]:
#Merged Both Years in Single Sheet

retail_df = pd.concat(
    [sheet_1, sheet_2],
    ignore_index=True 
)
print("retail_df.shape")

retail_df.shape

In [21]:
print(retail_df.shape)

(1067371, 8)

In [22]:
retail_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [23]:
retail_df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [24]:
retail_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

In [25]:
retail_df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [26]:
retail_df.duplicated().sum()

np.int64(34335)

In [27]:
retail_df.describe()

           Quantity                 InvoiceDate         Price    Customer ID
count  1.067371e+06                     1067371  1.067371e+06  824364.000000
mean   9.938898e+00  2011-01-02 21:13:55.394029  4.649388e+00   15324.638504
min   -8.099500e+04         2009-12-01 07:45:00 -5.359436e+04   12346.000000
25%    1.000000e+00         2010-07-09 09:46:00  1.250000e+00   13975.000000
50%    3.000000e+00         2010-12-07 15:28:00  2.100000e+00   15255.000000
75%    1.000000e+01         2011-07-22 10:23:00  4.150000e+00   16797.000000
max    8.099500e+04         2011-12-09 12:50:00  3.897000e+04   18287.000000
std    1.727058e+02                         NaN  1.235531e+02    1697.464450

In [28]:
retail_df.describe(include="object")

C:\Users\User\AppData\Local\Temp\ipykernel_12832\143765455.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  retail_df.describe(include="object")

        Invoice StockCode                         Description         Country
count   1067371   1067371                             1062989         1067371
unique    53628      5305                                5698              43
top      537434    85123A  WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
freq       1350      5829                                5918          981330

In [29]:
retail_df[
    retail_df ["Quantity"] <0
].shape

(22950, 8)

In [30]:
retail_df[
    retail_df ["Price"] < 0
].shape

(5, 8)

In [33]:
retail_df[
    retail_df ["Quantity"] <0
].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [34]:
retail_df[
    retail_df ["Price"] < 0
].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [35]:
retail_df[ 
    retail_df[ "Customer ID"].isnull()
].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom

In [36]:
retail_df[ 
    retail_df[ "Description"].isnull()
].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [37]:
retail_df.nunique()

Invoice        53628
StockCode       5305
Description     5698
Quantity        1057
InvoiceDate    47635
Price           2807
Customer ID     5942
Country           43
dtype: int64

In [38]:
retail_df[ 
    retail_df[ "Price"] == 0
].shape

(6202, 8)

In [40]:
retail_df[ 
    retail_df[ "Price"] == 0
].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom

In [41]:
retail_df["Country"].value_counts()

Country
United Kingdom          981330
EIRE                     17866
Germany                  17624
France                   14330
Netherlands               5140
Spain                     3811
Switzerland               3189
Belgium                   3123
Portugal                  2620
Australia                 1913
Channel Islands           1664
Italy                     1534
Norway                    1455
Sweden                    1364
Cyprus                    1176
Finland                   1049
Austria                    938
Denmark                    817
Unspecified                756
Greece                     663
Japan                      582
USA                        535
Poland                     535
United Arab Emirates       500
Israel                     371
Hong Kong                  364
Singapore                  346
Malta                      299
Iceland                    253
Canada                     228
Lithuania                  189
RSA                        169
Bahrain                    126
Brazil                      94
Thailand                    76
Korea                       63
European Community          61
Lebanon                     58
West Indies                 54
Bermuda                     34
Nigeria                     32
Czech Republic              30
Saudi Arabia                10
Name: count, dtype: int64

In [42]:
retail_df["Country"].nunique()

43

In [43]:
retail_df["Invoice"].astype(str).str.startswith("C").sum()

np.int64(19494)

In [46]:
retail_df[ 
    retail_df["Invoice"].astype(str).str.startswith("C")
].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [47]:
retail_df[ 
    retail_df["Invoice"].astype(str).str.startswith("C")
]["Quantity"].describe()

count    19494.000000
mean       -25.186827
std        805.104908
min     -80995.000000
25%         -6.000000
50%         -2.000000
75%         -1.000000
max          1.000000
Name: Quantity, dtype: float64

In [48]:
retail_df[ 
    retail_df["Invoice"].astype(str).str.startswith("C")
]["Price"].describe()

count    19494.000000
mean        44.872221
std        596.335291
min          0.010000
25%          1.450000
50%          2.950000
75%          6.750000
max      38970.000000
Name: Price, dtype: float64

In [49]:
retail_df[ 
    retail_df["Invoice"].astype(str).str.startswith("C")
]["Customer ID"].isnull().sum()

np.int64(750)

In [50]:
retail_df[ 
    retail_df["Invoice"].astype(str).str.startswith("C")
]["Country"].value_counts().head(10)

Country
United Kingdom     16650
Germany              921
EIRE                 512
France               389
USA                  126
Australia             98
Japan                 97
Channel Islands       95
Spain                 91
Italy                 66
Name: count, dtype: int64

In [51]:
retail_df[ 
    retail_df.duplicated()
].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
723,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
725,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
745,489536,21809,CHRISTMAS HANGING TREE WITH BELL,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom
799,489536,22142,CHRISTMAS CRAFT WHITE FAIRY,1,2009-12-01 12:13:00,1.45,16393.0,United Kingdom
808,489536,17164D,ASS COL SMALL SAND FROG P'WEIGHT,1,2009-12-01 12:13:00,0.42,16393.0,United Kingdom
809,489536,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,1,2009-12-01 12:13:00,2.55,16393.0,United Kingdom
810,489536,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2009-12-01 12:13:00,1.25,16393.0,United Kingdom
817,489536,22142,CHRISTMAS CRAFT WHITE FAIRY,1,2009-12-01 12:13:00,1.45,16393.0,United Kingdom
820,489536,21650,ASSORTED TUTTI FRUTTI BRACELET,1,2009-12-01 12:13:00,0.65,16393.0,United Kingdom

In [52]:
retail_df[ 
    retail_df.duplicated()
].shape

(34335, 8)

In [53]:
retail_df[ 
    retail_df["Invoice"]== "489517"
]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [54]:
retail_df[ 
    retail_df["Invoice"].astype(str)== "489517"
]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
361,489517,21705,BAG 500g SWIRLY MARBLES,1,2009-12-01 11:34:00,1.65,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
364,489517,16207A,PINK STRAWBERRY HANDBAG,2,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
366,489517,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
369,489517,21584,RETRO SPOT SMALL TUBE MATCHES,20,2009-12-01 11:34:00,1.65,16329.0,United Kingdom
370,489517,20972,PINK CREAM FELT CRAFT TRINKET BOX,1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
372,489517,21791,VINTAGE HEADS AND TAILS CARD GAME,6,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
373,489517,21790,VINTAGE SNAP CARDS,4,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
374,489517,21931,JUMBO STORAGE BAG SUKI,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
375,489517,20711,JUMBO BAG TOYS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
376,489517,47591A,CAROUSEL DES CHILD'S APRON,1,2009-12-01 11:34:00,1.65,16329.0,United Kingdom
377,489517,84997B,RED 3 PIECE MINI DOTS CUTLERY SET,12,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
378,489517,84997A,GREEN 3 PIECE MINI DOTS CUTLERY SET,12,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
380,489517,22122,SET OF 2 FANCY FONT TEA TOWELS,12,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
381,489517,20971,PINK BLUE FELT CRAFT TRINKET BOX,1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
382,489517,21252,SET OF MEADOW FLOWER STICKERS,1,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
387,489517,21837,CROSS STITCH ALPHABET CUSHION COVER,2,2009-12-01 11:34:00,5.95,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
389,489517,22335,HEART DECORATION PAINTED ZINC,1,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
392,489517,21791,VINTAGE HEADS AND TAILS CARD GAME,1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
393,489517,21790,VINTAGE SNAP CARDS,1,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
395,489517,85129A,"WHITE PEARL BEADED HEART, SMALL",1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
396,489517,84791,GINGHAM HEART DECORATION,1,2009-12-01 11:34:00,2.95,16329.0,United Kingdom
397,489517,21244,BLUE SPOTTY PLATE,4,2009-12-01 11:34:00,1.69,16329.0,United Kingdom
398,489517,20675,BLUE SPOTTY BOWL,4,2009-12-01 11:34:00,1.25,16329.0,United Kingdom

In [55]:
retail_df["InvoiceDate"].min()
retail_df["InvoiceDate"].max()

Timestamp('2011-12-09 12:50:00')

In [56]:
(retail_df["InvoiceDate"].min()-
retail_df["InvoiceDate"].max())

Timedelta('-739 days +18:55:00')

In [60]:
retail_df["InvoiceDate"].min()
retail_df["InvoiceDate"].max()

Timestamp('2011-12-09 12:50:00')

In [61]:
retail_df["InvoiceDate"].min()

Timestamp('2009-12-01 07:45:00')

In [63]:
retail_df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

In [64]:
retail_df.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
281246,516770,85061W,WHITE JEWELLED HEART DECORATION,1,2010-07-22 18:17:00,0.85,16549.0,United Kingdom
325938,521182,85224,ASSORTED COLOUR SILK GLASSES CASE,120,2010-09-02 16:14:00,0.38,14298.0,United Kingdom
519114,537645,22197,SMALL POPCORN HOLDER,24,2010-12-07 15:34:00,1.66,NaN,United Kingdom
844689,564843,72800E,4 IVORY DINNER CANDLES SILVER FLOCK,1,2011-08-30 14:09:00,2.55,15866.0,United Kingdom
488563,535221,22635,CHILDS BREAKFAST SET DOLLY GIRL,1,2010-11-25 12:21:00,9.95,12748.0,United Kingdom

In [65]:
retail_df["Customer ID"].nunique()

5942

In [66]:
retail_df["Invoice"].nunique()

53628

# Dataset Audit Summary

## Objective
Understand dataset structure, quality, completeness, and business relevance.

## Key Findings
- Dataset contains transactional retail sales data.
- Customer, product, invoice, pricing, and country information are available.
- Missing values and data quality issues were identified.
- Dataset is suitable for customer analytics and revenue analysis.

## Recommendations
- Remove invalid records before analysis.
- Standardize data types.
- Handle missing customer identifiers carefully.
- Validate revenue-related fields before business reporting.